// Package sakura is image resizer/optimizer (thumbnailler),
// as well as an aws s3-compatible uploader for generated files.
package sakura

// Uploader can upload thumbnails and images generated by sakura.
type Uploader interface {
	// UploadThumbnail takes a resized thumbnail byte buffer from Generator.ProcessThumbnail
	// and uploads it to s3 under the given name.
	UploadThumbnail(name string, buf []byte) error

	// UploadImage takes an image byte buffer from Generator.ProcessImage
	// and uploads it to s3 under the given name.
	UploadImage(name string, buf []byte) error
}

type Generator interface {
	// ProcessImage returns a basic image, as a byte buffer, processed however is set up.
	ProcessImage(buf []byte) ([]byte, error)

	// ProcessThumbnail should return a
	ProcessThumbnail(buf []byte) ([]byte, error)
}

// Config is a generic configuration struct for sakura.
type Config struct {
	// MaxWidth is the maximum width allowed in generated thumbnails.
	// Thumbnails will always respect the original's aspect ratio.
	MaxWidth uint

	// MaxHeight is the maximum height allowed in generated thumbnails.
	// Thumbnails will always respect the original's aspect ratio.
	MaxHeight uint
}
