// Package sakura is image resizer/optimizer (thumbnailler),
// as well as an aws s3-compatible uploader for generated files.
//
// This is just the base interfaces for the package.
// - see github.com/ameliaikeda/sakura/processor for an implementation of Generator
// - see github.com/ameliaikeda/sakura/uploader for an implementation of Uploader
// For the main executable, see cmd/sakura.
package sakura

import (
	"io"
)

// Uploader can upload thumbnails and images generated by sakura.
type Uploader interface {
	// UploadThumbnail takes a resized thumbnail byte buffer from Generator.ProcessThumbnail
	// and uploads it to s3 under the given name.
	UploadThumbnail(name string, buf []byte) error

	// UploadImage takes an image byte buffer from Generator.ProcessImage
	// and uploads it to s3 under the given name.
	UploadImage(name string, buf []byte) error
}

// Generator creates
type Generator interface {
	// ProcessImage returns a basic image, as a byte buffer, processed however is set up.
	ProcessImage(body io.Reader) ([]byte, error)

	// ProcessThumbnail returns a buffer holding resized thumbnails from the input body.
	ProcessThumbnail(body io.Reader) ([]byte, error)
}

// Config holds configuration parameters for image generator for thumbnails.
type GeneratorConfig struct {
	// MaxHeight is the (aspect-ratio-constrained) max height used for thumbnails, in pixels.
	// This is required.
	MaxHeight uint

	// MaxWidth is the (aspect-ratio-constrained) max width used for thumbnails, in pixels.
	// This is required.
	MaxWidth uint

	// Quality is the JPEG quality used for original main images.
	// If not given, the generator decides the value.
	Quality uint

	// ThumbnailQuality is the JPEG quality used for generating thumbnails.
	// If not given, the generator decides the value.
	ThumbnailQuality uint

	// ImageType is used to decide which format to use for image generation.
	// If not given, the generator decides the value.
	ImageType string
}

// Config is a basic configuration struct for an uploader.
type UploaderConfig struct {
	// ThumbnailBucket is the "bucket" (or folder) to upload thumbnails.
	ThumbnailBucket string

	// ImageBucket is the "bucket" (or folder) to upload main images.
	ImageBucket string
}
